### ISSUE TITLE
Test episodes contain duplicate data

### ISSUE THREAD

**Issue by roboak** [dikshant2210/Carla-CTS02#1]
https://github.com/dikshant2210/Carla-CTS02/blob/9664667f0f8cc24f47848e883fb72a022b1e1531/benchmark/environment/environment.py#L74

The for loop iterating over the scenes is running twice while generating episodes for model evaluation while training, thus increasing the size of test_episodes. 

Also, evaluating the model takes a lot of time as the number of episodes is large. Can we keep the batch size adaptive such that in the beginning, a rigorous evaluation is not done and towards the later stages of training, the evaluation batch size is increased? This can save us a lot of time in training these models.

**Comment by DP1997** [comment]
Hi @dikshant2210, 
I am currently working on evaluating new methods on the CARLA-CTS02 benchmark under Matthias and I was wondering how you trained the predictor m2p3 for HyLEAR exactly.
Unfortunately, there doesn't seem to be any particular script available for reproducing the model that you used in HyLEAR, but which is quite important for the sake of comparability. 
Would you mind elaborating on this shortly? E.g. What data was used and how was it pre-processed?
Thanks for you work!

**Comment by dikshant2210** [comment]
The episodes are divided into training, validation and testing. Line 74 gets the validation episodes, which can anyway be turned by changing self.setting variable. So depending on what you want to do, training or validation you can select the episodes.
