### ISSUE TITLE
M2P3 missing training specifications

### ISSUE THREAD

**Issue by DP1997** [dikshant2210/Carla-CTS02#2]
Hi @dikshant2210, 
I am currently working on evaluating new methods on the CARLA-CTS02 benchmark under Matthias and I was wondering how you trained the predictor m2p3 for HyLEAR exactly.
Unfortunately, there doesn't seem to be any particular script available for reproducing the model that you used in HyLEAR, but which is quite important for the sake of comparability. 
Would you mind elaborating on this shortly? E.g. What data was used and how was it pre-processed?
Thanks for you work!

**Comment by dikshant2210** [comment]
If I remember correctly, to collect the data for training m2p3 I ran all the training episodes of pedestrian scenarios and recorded pedestrian position for each timestep. I think I used 15 previous positions as input and predicted for next 20 positions. Therefore the recorded positions were divided into (15, 20) position tuples to be used as input for training. Unfortunately, I can't find this training data file anymore.

**Comment by DP1997** [comment]
> If I remember correctly, to collect the data for training m2p3 I ran all the training episodes of pedestrian scenarios and recorded pedestrian position for each timestep. I think I used 15 previous positions as input and predicted for next 20 positions. Therefore the recorded positions were divided into (15, 20) position tuples to be used as input for training. Unfortunately, I can't find this training data file anymore.

thanks i think i get the gist of it :)
